-- https://programmers.co.kr/learn/courses/30/lessons/59045
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE SUBSTRING_INDEX(INS.SEX_UPON_INTAKE, ' ', 1) != SUBSTRING_INDEX(OUTS.SEX_UPON_OUTCOME, ' ', 1)