-- https://programmers.co.kr/learn/courses/30/lessons/59411
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.DATETIME > INS.DATETIME
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2;