-- https://programmers.co.kr/learn/courses/30/lessons/59413

WITH RECURSIVE HOUR_TEMP(HOUR) AS
(
  SELECT 0
  UNION ALL
  SELECT HOUR + 1 FROM HOUR_TEMP WHERE HOUR < 23
)

SELECT a.HOUR, COUNT(HOUR(b.DATETIME))
FROM HOUR_TEMP a
LEFT JOIN ANIMAL_OUTS b
ON a.HOUR=HOUR(b.DATETIME)
GROUP BY 1
ORDER BY 1;